Nightly SVN Pull

diff --git a/wwiv-svn/builds/jenkins/wwiv/build b/wwiv-svn/builds/jenkins/wwiv/build
--- a/wwiv-svn/builds/jenkins/wwiv/build
+++ b/wwiv-svn/builds/jenkins/wwiv/build
@@ -9,23 +9,37 @@
 
 
 rm ${WORKSPACE}/wwiv-build-linux-*.zip
+rm ${WORKSPACE}/wwiv-build-linux-*.tar.gz
 
 set -e
 
-declare -r RELEASE_ZIP=${WORKSPACE}/wwiv-build-linux-${SVN_REVISION}-${BUILD_NUMBER}.zip
+declare -r RELEASE_TGZ=${WORKSPACE}/wwiv-build-linux-${SVN_REVISION}-${BUILD_NUMBER}.tar.gz
+echo "Workspace: ${WORKSPACE}"
+echo "Revision:  ${SVN_REVISION}"
+echo "Archive:   ${RELEASE_TGZ}"
+
+echo "Cleaning up release dir"
+if [[ -d "${WORKSPACE}/release" ]]
+then
+  rm -rf "${WORKSPACE}/release"
+fi
+mkdir -p "${WORKSPACE}/release"
+echo "Created release dir: ${WORKSPACE}/release"
+
+echo "Building binaries"
+cd ${WORKSPACE}
+sed -i -e "s@<#= version #>@${SVN_REVISION}@" bbs/version.template
 cmake .
 make -j12 
-echo "RELEASE_ZIP: ${RELEASE_ZIP}"
 
-if [[ ! -d "${WORKSPACE}/archives" ]]; then
-  mkdir -p "${WORKSPACE}/archives"
-  echo "Created archive dir: ${WORKSPACE}/archives"
-fi
-
-if [[ ! -d "${WORKSPACE}/release" ]]; then
-  mkdir -p "${WORKSPACE}/release"
-  echo "Created release dir: ${WORKSPACE}/release"
-fi
+echo "Populating built binaries"
+cp  ${WORKSPACE}/networkb/networkb \
+    ${WORKSPACE}/fix/fix \
+    ${WORKSPACE}/bbs/bbs \
+    ${WORKSPACE}/init/init \
+    ${WORKSPACE}/nodemgr/nodemgr \
+    ${WORKSPACE}/network/network \
+    ${WORKSPACE}/release
 
 echo "Creating Menus"
 cd ${WORKSPACE}/bbs/admin/menus/en
@@ -39,7 +53,34 @@ echo "Creating regions"
 cd ${WORKSPACE}/bbs/admin
 zip -r ${WORKSPACE}/release/regions.zip regions/*
 
-echo "Creating release archive: ${RELEASE_ZIP}"
-cd ${WORKSPACE}/release
-zip ${RELEASE_ZIP} *
+echo "adding common files"
+cd ${WORKSPACE}/bbs/admin
+shopt -s extglob
+set +e
+cp -v !(*.bat) ${WORKSPACE}/release
+RESULT=$?
+set -e
+# cp returns non-zero if we skip directories, so do our own check
+if [[ $RESULT -gt 1 ]]
+then
+  exit 1
+fi
+shopt -u extglob
 
+echo "adding linux-specific files"
+cd ${WORKSPACE}/bbs/admin/unix
+shopt -s dotglob
+cp -a * ${WORKSPACE}/release
+shopt -u dotglob
+
+echo "Creating build.nfo file"
+echo "Build URL ${BUILD_URL}" > ${WORKSPACE}/release/build.nfo
+echo "Subversion Build: ${SVN_REVISION}" >> ${WORKSPACE}/release/build.nfo
+
+echo "Creating release archive: ${RELEASE_TGZ}"
+cd ${WORKSPACE}/release
+tar zcvf ${RELEASE_TGZ} *
+
+echo "Archive file: ${RELEASE_TGZ}"
+echo "File Contents:"
+tar ztvf ${RELEASE_TGZ}
